### PR TITLE
Update IlluminateSnappyImage.php

### PR DESCRIPTION
**Pull request by szabizs**
/** Preventing conflict with Image facade **/

### CODE REVIEW

**Comment by barryvdh** [comment]
Which Image facade?

**Comment by szabizs** [comment]
Intervention Image -> most popular for Laravel.

**Comment by barryvdh** [comment]
But I'm not using that in my class at all?
Just change it in yout config/app.php facades

**Comment by szabizs** [comment]
I know you are not using it, but instead of `'Image' => Barryvdh\Snappy\Facades\SnappyImage::class`, it could be` 'SnappyImage' => Barryvdh\Snappy\Facades\SnappyImage::class` (i modified mine, but maybe someone will have this issue)

It really made me think a few minutes why I have errors untill I figured it out that it has the same facade.

**Comment by barryvdh** [comment]
You can change the readme, but this PR doesn't make sense.

**Pull request closed without merging**
