### PR TITLE
Support laravel 5.4

### PR DESCRIPTION
**Pull request by django23**

### CODE REVIEW

**Comment by barryvdh** [comment]
Does this news changes for 5.4?

**Comment by django23** [comment]
Hey @barryvdh,

I didn't get your question. 

Cheers,

**Comment by barryvdh** [comment]
*need

Does laravel-snappy need more changes to work with Laravel 5.4, or is it working correctly now? If so, I can tag a new version.

**Comment by django23** [comment]
Ah,

Well, finishing the last changes to my repo. I will let you know probably today. Need to make the tests work again and then check the result.

I keep you posted.

**Comment by django23** [comment]
Hoi @barryvdh,

It looks like it works on our side. As soon as the release is ready we will send it to staging. Keep you posted

**Comment by barryvdh** [comment]
Tagged v0.3.2 :)

**Pull request merged**
