### PR TITLE
Multiple views into one pdf

### PR DESCRIPTION
**Pull request by BTeodorWork**
Allow to merge multiple views into one pdf

### CODE REVIEW

**Comment by BTeodorWork** [comment]
Usage:

````
$pdf = PDF::loadView('pdf.invoice', $data)->loadView('pdf.invoice2', $data);
return $pdf->download('invoices.pdf');
````

**Comment by GrofGraf** [comment]
@BTeodorWork 

With your PR implemented, pdfs get merged even when I want to make them as separate pdfs.
(Let's say I want two attachments for my outgoing mail)

Example:
`
$pdf1 = PDF::loadView(pdf.invoice, $data);
$pdf2 = PDF::loadView('pdf.receipt, $data);
`

**Comment by barryvdh** [comment]
Yeah I can see this be useful, but could be breaking. Although it's actually more logical, so might be good for next version.

**Comment by herryswastika** [comment]
> Usage:
> 
> ```
> $pdf = PDF::loadView('pdf.invoice', $data)->loadView('pdf.invoice2', $data);
> return $pdf->download('invoices.pdf');
> ```

Thank you thank you. Just a simple fix, but powerful result. In my app, I have gojs, canvasjs, and of course eloquent which all those different pages needs to be combined into one single pdf and presented to Client. Now I dont have to use PDF Merge, because the output pdf has table of contents, page numbering, graphic, chart, cover page, etc etc. 
December 22 2018, Happy Holiday to all..

**Comment by herryswastika** [comment]
errghh... now how I opt these changes not to be overwritten by update? because the code is in vendor folder

**Comment by jellybobbin** [comment]
When merging, choose: Start from the last tail or a new page

**Pull request closed without merging**
