### PR TITLE
Use fully-qualified class names in return docblocks for download and stream methods of PdfWrapper

### PR DESCRIPTION
**Pull request by danieliancu**
Use fully-qualified class names in return docblocks for download and stream methods of PdfWrapper.

### CODE REVIEW

**Comment by barryvdh** [comment]
Why? The IDE should figure this out.

**Comment by danieliancu** [comment]
@barryvdh latest version of PhpStorm figures this out as `Barryvdh\Snappy\Response` instead of `\Illuminate\Http\Response` and generally I think this is a best practice to follow, but however you want.

**Comment by barryvdh** [comment]
Hmm kay, but it has conflicts now :(

You want to re-submit or should I change it?

**Comment by barryvdh** [comment]
Also, that's a PHP storm error, when the `use ...\Response` is used.

**Comment by danieliancu** [comment]
@barryvdh I agree on that, but I still think it's a good practice to follow.

I'll resubmit.
Thank you.

**Comment by danieliancu** [comment]
@barryvdh Thank you for the awesome package.

**Pull request closed without merging**
